### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by deeplylearner** [LegendLeoChen/yolov8-bird#3]
You can provide the dataset for training？

**Comment by LegendLeoChen** [comment]
yes, it has been uploaded.
baidudisk：https://pan.baidu.com/s/1IAbgjSZs9G7XmKPEwMiBdw?pwd=1213 提取码：1213

google：https://drive.google.com/drive/folders/12iIgp0_4aPTHtyqNYhfS4ZwWmwBjVXlE?usp=drive_link
