### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by Peterzhacodere** [LegendLeoChen/yolov8-bird#4]
你好，有没有训练好的模型

**Comment by LegendLeoChen** [comment]
百度网盘：https://pan.baidu.com/s/1IAbgjSZs9G7XmKPEwMiBdw?pwd=1213 提取码：1213

google：https://drive.google.com/drive/folders/12iIgp0_4aPTHtyqNYhfS4ZwWmwBjVXlE?usp=drive_link

**Comment by Peterzhacodere** [comment]
Thank you for your help. Wishing you all the best in everything you do

---- 回复的原邮件 ----
| 发件人 | Leo ***@***.***> |
| 发送日期 | 2024年11月16日 22:13 |
| 收件人 | LegendLeoChen/yolov8-bird ***@***.***> |
| 抄送人 | Peterzhacodere ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [LegendLeoChen/yolov8-bird] 模型 (Issue #4) |

Closed #4 as completed.
